spring:
  application:
    name: app

  datasource:
    url: jdbc:postgresql://localhost:5432/libitum_db
    username: libitum_user
    password: libitum_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID_LIBITUM} #Tengo como variable de entorno local los datos encriptados del cliente tanto el (¡id como el secret!) y así no expongo los valores en gitHub
            client-secret: ${GOOGLE_CLIENT_SECRET_LIBITUM}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

jwt:
  secret: clave_super_segura_para_hs384_con_48bytes!!! #Hay que cambiar esta clave porque es ridícula y ponerla como variable de entorno
  expiration: 3600000 # 1 hora en milisegundos
